name: proj_compras
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.3.1
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  google_maps_flutter: ^2.2.3
  http: 1.6.0
  url_launcher: ^6.1.11
  flutter_typeahead: ^5.2.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  intl: ^0.20.2

flutter:
  uses-material-design: true
  assets:
    - assets/logoappintegra.png
    - .env
